### PR TITLE
Send reminder function

### PR DESCRIPTION
**Pull request by ChanunyaO**
Send email as a reminder for item which the return date is within 2 days

### CODE REVIEW

**Comment by sujinunt** [comment]
This function can already send mail or not, I didn't see the mail that can send to user email in setting.

**Comment by ChanunyaO** [comment]
@sujinunt I just wrote another function to test the sending mail function whether it sends or not.

**Comment by pattanan-cyber** [comment]
Very nice!

**Comment by WhatWR** [comment]
teach me pls

**Pull request merged**
